### ISSUE TITLE
[Pocket] One Trust cookie banner throws a CORS / JS error

### ISSUE THREAD

**Issue by alexgibson** [mozilla/bedrock#14535]
## Description

Integration tests on main are failing for Pocket since the cookie banner there is not appearing: https://github.com/mozilla/bedrock/actions/runs/8906946806/job/24459945922

Test failure URL: https://dev.pocket.bedrock.nonprod.webservices.mozgcp.net/en/about/?automation=true

```
Access to XMLHttpRequest at 'https://cdn.cookielaw.org/consent/a7ff9c31-9f59-421f-9a8e-49b11a3eb24e-test/a7ff9c31-9f59-421f-9a8e-49b11a3eb24e-test.json' from origin 'https://dev.pocket.bedrock.nonprod.webservices.mozgcp.net' has been blocked by CORS policy: No 'Access-Control-Allow-Origin' header is present on the requested resource.
otSDKStub.js:1 Uncaught TypeError: Cannot read properties of undefined (reading 'Domain')
    at h.setDomainIfBulkDomainEnabled (otSDKStub.js:1:6528)
    at h.getLocation (otSDKStub.js:1:6967)
    at s.onerror (otSDKStub.js:1:9358)
cdn.cookielaw.org/consent/a7ff9c31-9f59-421f-9a8e-49b11a3eb24e-test/a7ff9c31-9f59-421f-9a8e-49b11a3eb24e-test.json:1 
Failed to load resource: net::ERR_FAILED
```

**Comment by alexgibson** [comment]
This has now been resolved on Pocket's side, closing
