### ISSUE TITLE
Can't add a page due to a blow-up in wagtaildraftsharing

### ISSUE THREAD

**Issue by stevejalim** [mozilla/bedrock#15291]
Just noticed that it's not possible to add a page of any tyoe to the CMS (local or on Dev) due to a blow-up in wagtaildraftsharing.

```
Traceback (most recent call last):
  File "/Users/steve/.pyenv/versions/bedrock/lib/python3.11/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "/Users/steve/.pyenv/versions/bedrock/lib/python3.11/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/steve/.pyenv/versions/bedrock/lib/python3.11/site-packages/django/views/decorators/cache.py", line 62, in _wrapper_view_func
    response = view_func(request, *args, **kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/steve/.pyenv/versions/bedrock/lib/python3.11/site-packages/wagtail/admin/urls/__init__.py", line 178, in wrapper
    return view_func(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/steve/.pyenv/versions/bedrock/lib/python3.11/site-packages/wagtail/admin/auth.py", line 153, in decorated_view
    response = view_func(request, *args, **kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/steve/.pyenv/versions/bedrock/lib/python3.11/site-packages/django/views/generic/base.py", line 104, in view
    return self.dispatch(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/steve/.pyenv/versions/bedrock/lib/python3.11/site-packages/wagtail/admin/views/pages/create.py", line 136, in dispatch
    return super().dispatch(request)
           ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/steve/.pyenv/versions/bedrock/lib/python3.11/site-packages/django/views/generic/base.py", line 143, in dispatch
    return handler(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/steve/.pyenv/versions/bedrock/lib/python3.11/site-packages/wagtail/admin/views/pages/create.py", line 341, in get
    return self.render_to_response(self.get_context_data())
                                   ^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/steve/.pyenv/versions/bedrock/lib/python3.11/site-packages/wagtail/admin/views/pages/create.py", line 384, in get_context_data
    action_menu = PageActionMenu(
                  ^^^^^^^^^^^^^^^
  File "/Users/steve/.pyenv/versions/bedrock/lib/python3.11/site-packages/wagtail/admin/action_menu.py", line 307, in __init__
    if menu_item.is_shown(self.context):
       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/steve/.pyenv/versions/bedrock/lib/python3.11/site-packages/wagtaildraftsharing/wagtail_hooks.py", line 66, in is_shown
    return context["page"].has_unpublished_changes
           ~~~~~~~^^^^^^^^
KeyError: 'page'

```

Fixing this now

**Comment by stevejalim** [comment]
Fixed o Dev - needs to roll to staging and prod
