### ISSUE TITLE
Missing `del` dependency in build

### ISSUE THREAD

**Issue by alexgibson** [mozilla/bedrock#6481]
Jenkins has started throwing an error building Protocol:

```
Error: Cannot find module 'del'
    at Function.Module._resolveFilename (module.js:476:15)
    at Function.Module._load (module.js:424:25)
    at Module.require (module.js:504:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/home/travis/build/mozilla/protocol/gulp/tasks/clean.js:2:13)
    at Module._compile (module.js:577:32)
    at Object.Module._extensions..js (module.js:586:10)
    at Module.load (module.js:494:32)
    at tryModuleLoad (module.js:453:12)
    at Function.Module._load (module.js:445:3)
```

https://travis-ci.org/mozilla/protocol/builds/455254829#L1682

It doesn't seem to happen for me locally, as `del` is a dependency of `eslint` (according to `npm ls del`), so the error may be dependent on the version of NPM. Still, `del` is a direct dependency in our project, so we should list it in `package.json`.

**Comment by stephaniehobson** [comment]
I think this issue was supposed to be in the protocol repo. There's supposed to be a [beta feature](https://help.github.com/articles/transferring-an-issue-to-another-repository/) in the right column to transfer issues but I don't have it.

**Comment by alexgibson** [comment]
> I think this issue was supposed to be in the protocol repo. There's supposed to be a beta feature in the right column to transfer issues but I don't have it.

Ah, good catch thanks!
