### ISSUE TITLE
Error in dev environment with Debug=False

### ISSUE THREAD

**Issue by stephaniehobson** [mozilla/bedrock#6617]
`DEBUG=False` causes pages to load as `A server error occurred.  Please contact the administrator.`

The error might be:

```
app_1         | ERROR 2018-12-14 11:42:10,970 base Internal Server Error: /en-US/favicon.ico
app_1         | Traceback (most recent call last):
app_1         |   File "/venv/lib/python2.7/site-packages/django/core/handlers/base.py", line 87, in get_exception_response
app_1         |     response = callback(request, **param_dict)
app_1         |   File "/venv/lib/python2.7/site-packages/django/utils/decorators.py", line 110, in _wrapped_view
app_1         |     response = view_func(request, *args, **kwargs)
app_1         |   File "/venv/lib/python2.7/site-packages/django/views/defaults.py", line 22, in page_not_found
app_1         |     body = template.render(context, request)
app_1         |   File "/venv/lib/python2.7/site-packages/django_jinja/backend.py", line 106, in render
app_1         |     return mark_safe(self.template.render(context))
app_1         |   File "/venv/lib/python2.7/site-packages/jinja2/environment.py", line 1008, in render
app_1         |     return self.environment.handle_exception(exc_info, True)
app_1         |   File "/venv/lib/python2.7/site-packages/jinja2/environment.py", line 780, in handle_exception
app_1         |     reraise(exc_type, exc_value, tb)
app_1         |   File "/app/bedrock/base/templates/404.html", line 7, in top-level template code
app_1         |     {% extends "base-pebbles.html" %}
app_1         |   File "/app/bedrock/base/templates/base-pebbles.html", line 10, in top-level template code
app_1         |     {{ js_bundle('site') }}
app_1         |   File "/app/bedrock/base/templatetags/helpers.py", line 127, in js_bundle
app_1         |     path = staticfiles_storage.url(path)
app_1         |   File "/venv/lib/python2.7/site-packages/django/contrib/staticfiles/storage.py", line 131, in url
app_1         |     hashed_name = self.stored_name(clean_name)
app_1         |   File "/venv/lib/python2.7/site-packages/django/contrib/staticfiles/storage.py", line 280, in stored_name
app_1         |     cache_name = self.clean_name(self.hashed_name(name))
app_1         |   File "/venv/lib/python2.7/site-packages/django/contrib/staticfiles/storage.py", line 94, in hashed_name
app_1         |     (clean_name, self))
app_1         | ValueError: The file 'js/BUNDLES/site.js' could not be found with <django.contrib.staticfiles.storage.ManifestStaticFilesStorage object at 0x7f1834322f90>.
app_1         | Traceback (most recent call last):
app_1         |   File "/usr/local/lib/python2.7/wsgiref/handlers.py", line 85, in run
app_1         |     self.result = application(self.environ, self.start_response)
app_1         |   File "/venv/lib/python2.7/site-packages/django/core/handlers/wsgi.py", line 189, in __call__
app_1         |     response = self.get_response(request)
app_1         |   File "/venv/lib/python2.7/site-packages/django/core/handlers/base.py", line 175, in get_response
app_1         |     response = self.get_exception_response(request, resolver, 404)
app_1         |   File "/venv/lib/python2.7/site-packages/django/core/handlers/base.py", line 90, in get_exception_response
app_1         |     response = self.handle_uncaught_exception(request, resolver, sys.exc_info())
app_1         |   File "/venv/lib/python2.7/site-packages/django/core/handlers/base.py", line 268, in handle_uncaught_exception
app_1         |     return callback(request, **param_dict)
app_1         |   File "/app/bedrock/base/views.py", line 150, in server_error_view
app_1         |     return l10n_utils.render(request, template_name, status=500)
app_1         |   File "/app/lib/l10n_utils/__init__.py", line 102, in render
app_1         |     return django_render(request, template, context, **kwargs)
app_1         |   File "/venv/lib/python2.7/site-packages/django/shortcuts.py", line 67, in render
app_1         |     template_name, context, request=request, using=using)
app_1         |   File "/venv/lib/python2.7/site-packages/django/template/loader.py", line 99, in render_to_string
app_1         |     return template.render(context, request)
app_1         |   File "/venv/lib/python2.7/site-packages/django_jinja/backend.py", line 106, in render
app_1         |     return mark_safe(self.template.render(context))
app_1         |   File "/venv/lib/python2.7/site-packages/jinja2/environment.py", line 1008, in render
app_1         |     return self.environment.handle_exception(exc_info, True)
app_1         |   File "/venv/lib/python2.7/site-packages/jinja2/environment.py", line 780, in handle_exception
app_1         |     reraise(exc_type, exc_value, tb)
app_1         |   File "/app/bedrock/base/templates/500.html", line 7, in top-level template code
app_1         |     {% extends "base-pebbles.html" %}
app_1         |   File "/app/bedrock/base/templates/base-pebbles.html", line 10, in top-level template code
app_1         |     {{ js_bundle('site') }}
app_1         |   File "/app/bedrock/base/templatetags/helpers.py", line 127, in js_bundle
app_1         |     path = staticfiles_storage.url(path)
app_1         |   File "/venv/lib/python2.7/site-packages/django/contrib/staticfiles/storage.py", line 131, in url
app_1         |     hashed_name = self.stored_name(clean_name)
app_1         |   File "/venv/lib/python2.7/site-packages/django/contrib/staticfiles/storage.py", line 280, in stored_name
app_1         |     cache_name = self.clean_name(self.hashed_name(name))
app_1         |   File "/venv/lib/python2.7/site-packages/django/contrib/staticfiles/storage.py", line 94, in hashed_name
app_1         |     (clean_name, self))
app_1         | ValueError: The file 'js/BUNDLES/site.js' could not be found with <django.contrib.staticfiles.storage.ManifestStaticFilesStorage object at 0x7f1834322f90>.
app_1         | [14/Dec/2018 11:42:11] "GET /en-US/favicon.ico HTTP/1.1" 500 59
```

**Comment by Shivansh2407** [comment]
Can you explain what should be done here?

**Comment by stephaniehobson** [comment]
I don't know since I'm not a back end dev.

I would start by trying to reproduce the error in a local development environment.

**Comment by NdagiStanley** [comment]
It seems that you're running this on docker, something I've done successfully.
I'm not getting the errors though.

@stephaniehobson can you recall what you did?
Which path you navigated to?
etc.

```
My System specs (if it helps):
Docker version 19.03.2, build 6a30dfc
OS: MacOS Version 10.14.6
```

**Comment by alexgibson** [comment]
Fixed in https://github.com/mozilla/bedrock/pull/8777
