### ISSUE TITLE
L10n string extraction is not wokring

### ISSUE THREAD

**Issue by alexgibson** [mozilla/bedrock#7181]
## Description

I'm trying to extract some strings for localization (see: https://github.com/mozilla/bedrock/issues/7177), however string extraction is not working for me and throws an error.

### Steps to reproduce

1. Start a virtualenv: `source venv/bin/activate`
2. Make sure dependencies are to up to date: `pip install -r requirements/dev.txt`
3. Run `./manage.py l10n_extract bedrock/firefox/templates/firefox/new/trailhead/thanks.html`

### Expected result

String extraction should work as expected.

### Actual result

The command throws an error:

```
usage: manage.py l10n_extract [-h] [--version] [-v {0,1,2,3}]
                              [--settings SETTINGS] [--pythonpath PYTHONPATH]
                              [--traceback] [--no-color]
manage.py l10n_extract: error: unrecognized arguments: bedrock/firefox/templates/firefox/new/trailhead/thanks.html
```

If I try the default command (i.e. to extract all strings) I see another error:

```
./manage.py l10n_extract
Traceback (most recent call last):
  File "./manage.py", line 10, in <module>
    execute_from_command_line(sys.argv)
  File "/Users/agibson/Documents/GitHub/bedrock/venv/lib/python2.7/site-packages/django/core/management/__init__.py", line 364, in execute_from_command_line
    utility.execute()
  File "/Users/agibson/Documents/GitHub/bedrock/venv/lib/python2.7/site-packages/django/core/management/__init__.py", line 356, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/Users/agibson/Documents/GitHub/bedrock/venv/lib/python2.7/site-packages/django/core/management/base.py", line 283, in run_from_argv
    self.execute(*args, **cmd_options)
  File "/Users/agibson/Documents/GitHub/bedrock/venv/lib/python2.7/site-packages/django/core/management/base.py", line 330, in execute
    output = self.handle(*args, **options)
  File "/Users/agibson/Documents/GitHub/bedrock/lib/l10n_utils/management/commands/l10n_extract.py", line 172, in handle
    gettext_extract()
  File "/Users/agibson/Documents/GitHub/bedrock/lib/l10n_utils/management/commands/l10n_extract.py", line 27, in gettext_extract
    call_command('extract', create=True)
  File "/Users/agibson/Documents/GitHub/bedrock/venv/lib/python2.7/site-packages/django/core/management/__init__.py", line 114, in call_command
    command = load_command_class(app_name, command_name)
  File "/Users/agibson/Documents/GitHub/bedrock/venv/lib/python2.7/site-packages/django/core/management/__init__.py", line 40, in load_command_class
    module = import_module('%s.management.commands.%s' % (app_name, name))
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/importlib/__init__.py", line 37, in import_module
    __import__(name)
  File "/Users/agibson/Documents/GitHub/bedrock/venv/lib/python2.7/site-packages/puente/management/commands/extract.py", line 10, in <module>
    class Command(BaseCommand):
  File "/Users/agibson/Documents/GitHub/bedrock/venv/lib/python2.7/site-packages/puente/management/commands/extract.py", line 13, in Command
    option_list = BaseCommand.option_list + (
AttributeError: type object 'BaseCommand' has no attribute 'option_list'
```

### Environment

I've tried scrapping my virtualenv and building it again from scratch, but to no avail. I feel like this is probably quite simple, and it's just a case of some syntax that has changed. But the docs don't seem to be accurate if so.

**Comment by alexgibson** [comment]
@pmac I feel like I'm probably missing something obvious here, any ideas?

**Comment by pmac** [comment]
Looks like this was missed during the Django 1.11 upgrade. I can try to get a PR together shortly.
