### ISSUE TITLE
Django error handling issues?

### ISSUE THREAD

**Issue by alexgibson** [mozilla/bedrock#8624]
## Description

This may well be a problem isolated to my environment, but since a few weeks or so I've no longer been able to get any useful error messages or tracebacks from Django during local dev. Whenever there's an error in a template for example, instead of the usual error page I only see this:

![image](https://user-images.githubusercontent.com/400117/75870476-ec8f9600-5e02-11ea-860f-2497ea1c08a9.png)

Looking in the console I don't get any good traceback either. The error is nearly always:

```
 Traceback (most recent call last):
[0]   File "/usr/local/Cellar/python/3.7.4_1/Frameworks/Python.framework/Versions/3.7/lib/python3.7/wsgiref/handlers.py", line 137, in run
[0]     self.result = application(self.environ, self.start_response)
[0]   File "/Users/agibson/Documents/GitHub/bedrock/venv/lib/python3.7/site-packages/django/contrib/staticfiles/handlers.py", line 65, in __call__
[0]     return self.application(environ, start_response)
[0]   File "/Users/agibson/Documents/GitHub/bedrock/venv/lib/python3.7/site-packages/django/core/handlers/wsgi.py", line 141, in __call__
[0]     response = self.get_response(request)
[0]   File "/Users/agibson/Documents/GitHub/bedrock/venv/lib/python3.7/site-packages/django/core/handlers/base.py", line 75, in get_response
[0]     response = self._middleware_chain(request)
[0]   File "/Users/agibson/Documents/GitHub/bedrock/venv/lib/python3.7/site-packages/django/core/handlers/exception.py", line 36, in inner
[0]     response = response_for_exception(request, exc)
[0]   File "/Users/agibson/Documents/GitHub/bedrock/venv/lib/python3.7/site-packages/django/core/handlers/exception.py", line 90, in response_for_exception
[0]     response = handle_uncaught_exception(request, get_resolver(get_urlconf()), sys.exc_info())
[0]   File "/Users/agibson/Documents/GitHub/bedrock/venv/lib/python3.7/site-packages/django/core/handlers/exception.py", line 125, in handle_uncaught_exception
[0]     return debug.technical_500_response(request, *exc_info)
[0]   File "/Users/agibson/Documents/GitHub/bedrock/venv/lib/python3.7/site-packages/django/views/debug.py", line 94, in technical_500_response
[0]     html = reporter.get_traceback_html()
[0]   File "/Users/agibson/Documents/GitHub/bedrock/venv/lib/python3.7/site-packages/django/views/debug.py", line 333, in get_traceback_html
[0]     c = Context(self.get_traceback_data(), use_l10n=False)
  File "/Users/agibson/Documents/GitHub/bedrock/venv/lib/python3.7/site-packages/django/views/debug.py", line 264, in get_traceback_data
[0]     frames = self.get_traceback_frames()
[0]   File "/Users/agibson/Documents/GitHub/bedrock/venv/lib/python3.7/site-packages/django/views/debug.py", line 422, in get_traceback_frames
[0]     filename, lineno, 7, loader, module_name,
[0]   File "/Users/agibson/Documents/GitHub/bedrock/venv/lib/python3.7/site-packages/django/views/debug.py", line 383, in _get_lines_from_file
[0]     context_line = source[lineno]
[0] IndexError: list index out of range
```

I seem to have the same issue running either in docker or natively.

**Comment by alexgibson** [comment]
@pmac any ideas here, or further information I could provide?

**Comment by alexgibson** [comment]
As a simple STR, open the [home page template](https://github.com/mozilla/bedrock/blob/master/bedrock/mozorg/templates/mozorg/home/home-en.html), go to down to the `billboard` macro on [line 93](https://github.com/mozilla/bedrock/blob/master/bedrock/mozorg/templates/mozorg/home/home-en.html#L93) and try renaming `billboard` to `typo`.

**Comment by pmac** [comment]
Huh. I saw that too once but figured it must be something strange in my environment. I'll investigate. I'd think it'd either be the debug output or our configured 500 error page if it was running with `DEBUG=False`.

**Comment by pmac** [comment]
Looks like we've hit this https://github.com/niwinz/django-jinja/issues/238

I'll see about upgrading Jinja and django-jinja to latest versions and see if that helps.
