### ISSUE TITLE
Error when viewing pages locally with dev=True, debug=False

### ISSUE THREAD

**Issue by alexgibson** [mozilla/bedrock#8636]
## Description

When running bedrock locally with `dev=True` and `debug=False`, pages throw an error.

### Steps to reproduce

1. In your `.env`, set `dev=True`, `debug=False` and start bedrock running.
2. Try loading any page e.g. http://localhost:8000/en-US/

### Expected result

The page should load without error.

### Actual result

The page displays the error message:

```
A server error occurred.  Please contact the administrator.
```

In the terminal session I see:

```
[0] During handling of the above exception, another exception occurred:
[0] 
[0] Traceback (most recent call last):
[0]   File "/usr/local/Cellar/python/3.7.4_1/Frameworks/Python.framework/Versions/3.7/lib/python3.7/wsgiref/handlers.py", line 137, in run
[0]     self.result = application(self.environ, self.start_response)
[0]   File "/Users/agibson/Documents/GitHub/bedrock/venv/lib/python3.7/site-packages/django/core/handlers/wsgi.py", line 141, in __call__
[0]     response = self.get_response(request)
[0]   File "/Users/agibson/Documents/GitHub/bedrock/venv/lib/python3.7/site-packages/django/core/handlers/base.py", line 75, in get_response
[0]     response = self._middleware_chain(request)
[0]   File "/Users/agibson/Documents/GitHub/bedrock/venv/lib/python3.7/site-packages/django/core/handlers/exception.py", line 36, in inner
[0]     response = response_for_exception(request, exc)
[0]   File "/Users/agibson/Documents/GitHub/bedrock/venv/lib/python3.7/site-packages/django/core/handlers/exception.py", line 90, in response_for_exception
[0]     response = handle_uncaught_exception(request, get_resolver(get_urlconf()), sys.exc_info())
[0]   File "/Users/agibson/Documents/GitHub/bedrock/venv/lib/python3.7/site-packages/django/core/handlers/exception.py", line 129, in handle_uncaught_exception
[0]     return callback(request, **param_dict)
[0]   File "/Users/agibson/Documents/GitHub/bedrock/bedrock/base/views.py", line 171, in server_error_view
[0]     return l10n_utils.render(request, template_name, status=500)
[0]   File "/Users/agibson/Documents/GitHub/bedrock/lib/l10n_utils/__init__.py", line 120, in render
[0]     return django_render(request, template, context, **kwargs)
[0]   File "/Users/agibson/Documents/GitHub/bedrock/venv/lib/python3.7/site-packages/django/shortcuts.py", line 36, in render
[0]     content = loader.render_to_string(template_name, context, request, using=using)
[0]   File "/Users/agibson/Documents/GitHub/bedrock/venv/lib/python3.7/site-packages/django/template/loader.py", line 62, in render_to_string
[0]     return template.render(context, request)
[0]   File "/Users/agibson/Documents/GitHub/bedrock/venv/lib/python3.7/site-packages/django_jinja/backend.py", line 63, in render
[0]     return mark_safe(self._process_template(self.template.render, context, request))
[0]   File "/Users/agibson/Documents/GitHub/bedrock/venv/lib/python3.7/site-packages/django_jinja/backend.py", line 109, in _process_template
[0]     return handler(context)
[0]   File "/Users/agibson/Documents/GitHub/bedrock/venv/lib/python3.7/site-packages/jinja2/environment.py", line 1090, in render
[0]     self.environment.handle_exception()
[0]   File "/Users/agibson/Documents/GitHub/bedrock/venv/lib/python3.7/site-packages/jinja2/environment.py", line 832, in handle_exception
[0]     reraise(*rewrite_traceback_stack(source=source))
[0]   File "/Users/agibson/Documents/GitHub/bedrock/venv/lib/python3.7/site-packages/jinja2/_compat.py", line 28, in reraise
[0]     raise value.with_traceback(tb)
[0]   File "/Users/agibson/Documents/GitHub/bedrock/bedrock/base/templates/500.html", line 7, in top-level template code
[0]     {% extends "base-pebbles.html" %}
[0]   File "/Users/agibson/Documents/GitHub/bedrock/bedrock/base/templates/base-pebbles.html", line 9, in top-level template code
[0]     {{ js_bundle('site') }}
[0]   File "/Users/agibson/Documents/GitHub/bedrock/bedrock/base/templatetags/helpers.py", line 129, in js_bundle
[0]     path = staticfiles_storage.url(path)
[0]   File "/Users/agibson/Documents/GitHub/bedrock/venv/lib/python3.7/site-packages/django/contrib/staticfiles/storage.py", line 153, in url
[0]     return self._url(self.stored_name, name, force)
[0]   File "/Users/agibson/Documents/GitHub/bedrock/venv/lib/python3.7/site-packages/django/contrib/staticfiles/storage.py", line 132, in _url
[0]     hashed_name = hashed_name_func(*args)
[0]   File "/Users/agibson/Documents/GitHub/bedrock/venv/lib/python3.7/site-packages/django/contrib/staticfiles/storage.py", line 420, in stored_name
[0]     raise ValueError("Missing staticfiles manifest entry for '%s'" % clean_name)
[0] ValueError: Missing staticfiles manifest entry for 'js/BUNDLES/site.js'
[0] ERROR 2020-03-09 09:35:58,683 basehttp "GET /en-US/ HTTP/1.1" 500 59
```

### Environment

N/A

**Comment by alexgibson** [comment]
/cc @pmac 

@Errolyn noticed this issue when trying to trigger rendering the 404/500 pages locally. It seems to be a problem with any template however. Any ideas?

**Comment by alexgibson** [comment]
/me notices this could be a duplicate of https://github.com/mozilla/bedrock/issues/6617

**Comment by pmac** [comment]
yeah. it's a bit of a pain to get the site running in prod mode locally. I'll see if I can get something better working and documented.

**Comment by alexgibson** [comment]
Fixed in https://github.com/mozilla/bedrock/pull/8777
