### ISSUE TITLE
[local dev] Fluent error when reloading pages

### ISSUE THREAD

**Issue by alexgibson** [mozilla/bedrock#8705]
## Description

When I'm working on a local dev environment, with a page open (say http://127.0.0.1:8000/en-US/firefox/privacy/products/), if I hit save on an .scss file (any file) to trigger a build/reload, bedrock sometimes throws a Fluent related error.

### Steps to reproduce

1. Start bedrock running locally.
2. Open a page e.g. http://127.0.0.1:8000/en-US/firefox/privacy/products/
3. Open an scss file and hit save to trigger a rebuild (you might have to try multiple times to hit the issue).

### Expected result

The page should build / reload.

### Actual result

Bedrock sometimes throws an error with `ValueError: generator already executing`. Usually reloading the page a second time makes the error go away.

```
System check identified no issues (0 silenced).
[0] March 26, 2020 - 07:02:59
[0] Django version 2.2.11, using settings 'bedrock.settings'
[0] Starting development server at http://0.0.0.0:8080/
[0] Quit the server with CONTROL-C.
[0] INFO 2020-03-26 07:03:20,169 basehttp "GET /en-US/ HTTP/1.1" 304 0
[1] [14:03:28] building: css/BUNDLES/windows-64-bit.css
[1] [Browsersync] Reloading Browsers...
[0] INFO 2020-03-26 07:03:29,868 basehttp "GET /en-US/ HTTP/1.1" 200 187517
[0] ERROR 2020-03-26 07:03:30,309 log Internal Server Error: /en-US/firefox/accounts/
[0] Traceback (most recent call last):
[0]   File "/Users/agibson/Documents/GitHub/bedrock/venv/lib/python3.7/site-packages/django/core/handlers/exception.py", line 34, in inner
[0]     response = get_response(request)
[0]   File "/Users/agibson/Documents/GitHub/bedrock/venv/lib/python3.7/site-packages/django/core/handlers/base.py", line 115, in _get_response
[0]     response = self.process_exception_by_middleware(e, request)
[0]   File "/Users/agibson/Documents/GitHub/bedrock/venv/lib/python3.7/site-packages/django/core/handlers/base.py", line 113, in _get_response
[0]     response = wrapped_callback(request, *callback_args, **callback_kwargs)
[0]   File "/Users/agibson/Documents/GitHub/bedrock/bedrock/firefox/views.py", line 777, in firefox_accounts
[0]     return l10n_utils.render(request, 'firefox/accounts-2019.html')
[0]   File "/Users/agibson/Documents/GitHub/bedrock/lib/l10n_utils/__init__.py", line 127, in render
[0]     return django_render(request, template, context, **kwargs)
[0]   File "/Users/agibson/Documents/GitHub/bedrock/venv/lib/python3.7/site-packages/django/shortcuts.py", line 36, in render
[0]     content = loader.render_to_string(template_name, context, request, using=using)
[0]   File "/Users/agibson/Documents/GitHub/bedrock/venv/lib/python3.7/site-packages/django/template/loader.py", line 62, in render_to_string
[0]     return template.render(context, request)
[0]   File "/Users/agibson/Documents/GitHub/bedrock/venv/lib/python3.7/site-packages/django_jinja/backend.py", line 63, in render
[0]     return mark_safe(self._process_template(self.template.render, context, request))
[0]   File "/Users/agibson/Documents/GitHub/bedrock/venv/lib/python3.7/site-packages/django_jinja/backend.py", line 109, in _process_template
[0]     return handler(context)
[0]   File "/Users/agibson/Documents/GitHub/bedrock/venv/lib/python3.7/site-packages/jinja2/environment.py", line 1090, in render
[0]     self.environment.handle_exception()
[0]   File "/Users/agibson/Documents/GitHub/bedrock/venv/lib/python3.7/site-packages/jinja2/environment.py", line 832, in handle_exception
[0]     reraise(*rewrite_traceback_stack(source=source))
[0]   File "/Users/agibson/Documents/GitHub/bedrock/venv/lib/python3.7/site-packages/jinja2/_compat.py", line 28, in reraise
[0]     raise value.with_traceback(tb)
[0]   File "/Users/agibson/Documents/GitHub/bedrock/bedrock/firefox/templates/firefox/accounts-2019.html", line 12, in top-level template code
[0]     {% set _utm_campaign = 'trailhead' %}
[0]   File "/Users/agibson/Documents/GitHub/bedrock/bedrock/firefox/templates/firefox/base/base-protocol.html", line 5, in top-level template code
[0]     {% extends "base-protocol.html" %}
[0]   File "/Users/agibson/Documents/GitHub/bedrock/bedrock/base/templates/base-protocol.html", line 1, in top-level template code
[0]     {% extends 'base-pebbles.html' %}
[0]   File "/Users/agibson/Documents/GitHub/bedrock/bedrock/base/templates/base-pebbles.html", line 95, in top-level template code
[0]     {% block site_header %}
[0]   File "/Users/agibson/Documents/GitHub/bedrock/bedrock/firefox/templates/firefox/accounts-2019.html", line 36, in block "site_header"
[0]     {% block page_css %}
[0]   File "/Users/agibson/Documents/GitHub/bedrock/bedrock/base/templates/includes/protocol/navigation/menu-firefox/index.html", line 10, in top-level template code
[0]     <button class="mzp-c-navigation-menu-button" type="button" aria-controls="mzp-c-navigation-items">{{ ftl('navigation-menu') }}</button>
[0]   File "/Users/agibson/Documents/GitHub/bedrock/lib/l10n_utils/templatetags/fluent.py", line 26, in ftl
[0]     return jinja2.Markup(fluent.translate(ctx['fluent_l10n'], message_id, fallback, **kwargs))
[0]   File "/Users/agibson/Documents/GitHub/bedrock/lib/l10n_utils/fluent.py", line 112, in inner
[0]     value = f(*args, **kwargs)
[0]   File "/Users/agibson/Documents/GitHub/bedrock/lib/l10n_utils/fluent.py", line 196, in translate
[0]     return l10n.format_value(message_id, kwargs)
[0]   File "/Users/agibson/Documents/GitHub/bedrock/venv/lib/python3.7/site-packages/fluent/runtime/fallback.py", line 34, in format_value
[0]     for bundle in self._bundles():
[0]   File "/Users/agibson/Documents/GitHub/bedrock/venv/lib/python3.7/site-packages/fluent/runtime/fallback.py", line 54, in _bundles
[0]     self._bundle_cache.append(next(self._bundle_it))
[0] ValueError: generator already executing
[0] ERROR 2020-03-26 07:03:30,314 basehttp "GET /en-US/firefox/accounts/ HTTP/1.1" 500 430227
```

### Environment

macOS 10.15.3

**Comment by pmac** [comment]
That's very odd. The docker container doing the rebuilding of the .scss file is not the same one running Django and throwing this error. I'll see if I can figure anything out.

**Comment by alexgibson** [comment]
> That's very odd. The docker container doing the rebuilding of the .scss file is not the same one running Django and throwing this error. I'll see if I can figure anything out.

Sorry I should note that I'm running bedrock using local installation (I find it much less resource hungry than docker).

This bug could also be a side effect of having more than one tab / page open at the same time.

**Comment by pmac** [comment]
I think this is due to the Fluent cache not being thread safe and the dev server loading the same page simultaneously. One solution is to turn off the cache for Fluent in dev mode. I'll keep looking at the Fluent implementation for a fix though.
