### ISSUE TITLE
Local install fails when installing Pillow

### ISSUE THREAD

**Issue by alexgibson** [mozilla/bedrock#9370]
## Description

I updated my local install of Yarn using `brew upgrade yarn`. However when homebrew updated, it looks like it also updated the version of Python installed on my machine. As a result, my local install of bedrock broke, and I can't install a fresh virtual env using the docs. It fails with an error.

### Steps to reproduce

Follow the local install steps here: https://bedrock.readthedocs.io/en/latest/install.html#local-installation

### Expected result

Bedrock should install successfully.

### Actual result

An error is thrown when installing Pillow:

```
   Running setup.py install for Pillow ... error
    ERROR: Command errored out with exit status 1:
     command: /Users/agibson/Documents/GitHub/bedrock/venv/bin/python3 -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/private/var/folders/sy/tzj820zd5vb4nv6wfgxcl2rr0000gn/T/pip-install-yasp_tsp/pillow/setup.py'"'"'; __file__='"'"'/private/var/folders/sy/tzj820zd5vb4nv6wfgxcl2rr0000gn/T/pip-install-yasp_tsp/pillow/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' install --record /private/var/folders/sy/tzj820zd5vb4nv6wfgxcl2rr0000gn/T/pip-record-v18v5jll/install-record.txt --single-version-externally-managed --compile --install-headers /Users/agibson/Documents/GitHub/bedrock/venv/include/site/python3.8/Pillow
         cwd: /private/var/folders/sy/tzj820zd5vb4nv6wfgxcl2rr0000gn/T/pip-install-yasp_tsp/pillow/
    Complete output (174 lines):
    running install
    running build
    running build_py
    creating build
    creating build/lib.macosx-10.15-x86_64-3.8
    creating build/lib.macosx-10.15-x86_64-3.8/PIL
    copying src/PIL/MpoImagePlugin.py -> build/lib.macosx-10.15-x86_64-3.8/PIL
    copying src/PIL/ImageMode.py -> build/lib.macosx-10.15-x86_64-3.8/PIL
    copying src/PIL/PngImagePlugin.py -> build/lib.macosx-10.15-x86_64-3.8/PIL
    copying src/PIL/XbmImagePlugin.py -> build/lib.macosx-10.15-x86_64-3.8/PIL
    copying src/PIL/PcxImagePlugin.py -> build/lib.macosx-10.15-x86_64-3.8/PIL
    copying src/PIL/SunImagePlugin.py -> build/lib.macosx-10.15-x86_64-3.8/PIL
    copying src/PIL/ImageFile.py -> build/lib.macosx-10.15-x86_64-3.8/PIL
    copying src/PIL/SpiderImagePlugin.py -> build/lib.macosx-10.15-x86_64-3.8/PIL
    copying src/PIL/TarIO.py -> build/lib.macosx-10.15-x86_64-3.8/PIL
    copying src/PIL/FitsStubImagePlugin.py -> build/lib.macosx-10.15-x86_64-3.8/PIL
    copying src/PIL/MpegImagePlugin.py -> build/lib.macosx-10.15-x86_64-3.8/PIL
    copying src/PIL/BdfFontFile.py -> build/lib.macosx-10.15-x86_64-3.8/PIL
    copying src/PIL/GribStubImagePlugin.py -> build/lib.macosx-10.15-x86_64-3.8/PIL
    copying src/PIL/ImageStat.py -> build/lib.macosx-10.15-x86_64-3.8/PIL
    copying src/PIL/PixarImagePlugin.py -> build/lib.macosx-10.15-x86_64-3.8/PIL
    copying src/PIL/GimpPaletteFile.py -> build/lib.macosx-10.15-x86_64-3.8/PIL
    copying src/PIL/ImageColor.py -> build/lib.macosx-10.15-x86_64-3.8/PIL
    copying src/PIL/ContainerIO.py -> build/lib.macosx-10.15-x86_64-3.8/PIL
    copying src/PIL/MspImagePlugin.py -> build/lib.macosx-10.15-x86_64-3.8/PIL
    copying src/PIL/MicImagePlugin.py -> build/lib.macosx-10.15-x86_64-3.8/PIL
    copying src/PIL/_version.py -> build/lib.macosx-10.15-x86_64-3.8/PIL
    copying src/PIL/ImtImagePlugin.py -> build/lib.macosx-10.15-x86_64-3.8/PIL
    copying src/PIL/GifImagePlugin.py -> build/lib.macosx-10.15-x86_64-3.8/PIL
    copying src/PIL/PalmImagePlugin.py -> build/lib.macosx-10.15-x86_64-3.8/PIL
    copying src/PIL/ImageQt.py -> build/lib.macosx-10.15-x86_64-3.8/PIL
    copying src/PIL/ImageMath.py -> build/lib.macosx-10.15-x86_64-3.8/PIL
    copying src/PIL/PaletteFile.py -> build/lib.macosx-10.15-x86_64-3.8/PIL
    copying src/PIL/FontFile.py -> build/lib.macosx-10.15-x86_64-3.8/PIL
    copying src/PIL/PdfParser.py -> build/lib.macosx-10.15-x86_64-3.8/PIL
    copying src/PIL/ExifTags.py -> build/lib.macosx-10.15-x86_64-3.8/PIL
    copying src/PIL/ImageCms.py -> build/lib.macosx-10.15-x86_64-3.8/PIL
    copying src/PIL/FpxImagePlugin.py -> build/lib.macosx-10.15-x86_64-3.8/PIL
    copying src/PIL/ImageChops.py -> build/lib.macosx-10.15-x86_64-3.8/PIL
    copying src/PIL/BufrStubImagePlugin.py -> build/lib.macosx-10.15-x86_64-3.8/PIL
    copying src/PIL/PSDraw.py -> build/lib.macosx-10.15-x86_64-3.8/PIL
    copying src/PIL/PcdImagePlugin.py -> build/lib.macosx-10.15-x86_64-3.8/PIL
    copying src/PIL/ImageFilter.py -> build/lib.macosx-10.15-x86_64-3.8/PIL
    copying src/PIL/ImageDraw2.py -> build/lib.macosx-10.15-x86_64-3.8/PIL
    copying src/PIL/ImagePath.py -> build/lib.macosx-10.15-x86_64-3.8/PIL
    copying src/PIL/DcxImagePlugin.py -> build/lib.macosx-10.15-x86_64-3.8/PIL
    copying src/PIL/__init__.py -> build/lib.macosx-10.15-x86_64-3.8/PIL
    copying src/PIL/JpegPresets.py -> build/lib.macosx-10.15-x86_64-3.8/PIL
    copying src/PIL/Hdf5StubImagePlugin.py -> build/lib.macosx-10.15-x86_64-3.8/PIL
    copying src/PIL/features.py -> build/lib.macosx-10.15-x86_64-3.8/PIL
    copying src/PIL/ImageDraw.py -> build/lib.macosx-10.15-x86_64-3.8/PIL
    copying src/PIL/GimpGradientFile.py -> build/lib.macosx-10.15-x86_64-3.8/PIL
    copying src/PIL/ImageWin.py -> build/lib.macosx-10.15-x86_64-3.8/PIL
    copying src/PIL/IcoImagePlugin.py -> build/lib.macosx-10.15-x86_64-3.8/PIL
    copying src/PIL/_tkinter_finder.py -> build/lib.macosx-10.15-x86_64-3.8/PIL
    copying src/PIL/EpsImagePlugin.py -> build/lib.macosx-10.15-x86_64-3.8/PIL
    copying src/PIL/TgaImagePlugin.py -> build/lib.macosx-10.15-x86_64-3.8/PIL
    copying src/PIL/ImageMorph.py -> build/lib.macosx-10.15-x86_64-3.8/PIL
    copying src/PIL/Jpeg2KImagePlugin.py -> build/lib.macosx-10.15-x86_64-3.8/PIL
    copying src/PIL/WalImageFile.py -> build/lib.macosx-10.15-x86_64-3.8/PIL
    copying src/PIL/PcfFontFile.py -> build/lib.macosx-10.15-x86_64-3.8/PIL
    copying src/PIL/BlpImagePlugin.py -> build/lib.macosx-10.15-x86_64-3.8/PIL
    copying src/PIL/ImageTk.py -> build/lib.macosx-10.15-x86_64-3.8/PIL
    copying src/PIL/GbrImagePlugin.py -> build/lib.macosx-10.15-x86_64-3.8/PIL
    copying src/PIL/ImageOps.py -> build/lib.macosx-10.15-x86_64-3.8/PIL
    copying src/PIL/PdfImagePlugin.py -> build/lib.macosx-10.15-x86_64-3.8/PIL
    copying src/PIL/ImageShow.py -> build/lib.macosx-10.15-x86_64-3.8/PIL
    copying src/PIL/ImageEnhance.py -> build/lib.macosx-10.15-x86_64-3.8/PIL
    copying src/PIL/WmfImagePlugin.py -> build/lib.macosx-10.15-x86_64-3.8/PIL
    copying src/PIL/ImageGrab.py -> build/lib.macosx-10.15-x86_64-3.8/PIL
    copying src/PIL/WebPImagePlugin.py -> build/lib.macosx-10.15-x86_64-3.8/PIL
    copying src/PIL/FliImagePlugin.py -> build/lib.macosx-10.15-x86_64-3.8/PIL
    copying src/PIL/TiffTags.py -> build/lib.macosx-10.15-x86_64-3.8/PIL
    copying src/PIL/CurImagePlugin.py -> build/lib.macosx-10.15-x86_64-3.8/PIL
    copying src/PIL/_util.py -> build/lib.macosx-10.15-x86_64-3.8/PIL
    copying src/PIL/GdImageFile.py -> build/lib.macosx-10.15-x86_64-3.8/PIL
    copying src/PIL/TiffImagePlugin.py -> build/lib.macosx-10.15-x86_64-3.8/PIL
    copying src/PIL/IptcImagePlugin.py -> build/lib.macosx-10.15-x86_64-3.8/PIL
    copying src/PIL/ImagePalette.py -> build/lib.macosx-10.15-x86_64-3.8/PIL
    copying src/PIL/BmpImagePlugin.py -> build/lib.macosx-10.15-x86_64-3.8/PIL
    copying src/PIL/ImageTransform.py -> build/lib.macosx-10.15-x86_64-3.8/PIL
    copying src/PIL/IcnsImagePlugin.py -> build/lib.macosx-10.15-x86_64-3.8/PIL
    copying src/PIL/McIdasImagePlugin.py -> build/lib.macosx-10.15-x86_64-3.8/PIL
    copying src/PIL/XpmImagePlugin.py -> build/lib.macosx-10.15-x86_64-3.8/PIL
    copying src/PIL/DdsImagePlugin.py -> build/lib.macosx-10.15-x86_64-3.8/PIL
    copying src/PIL/ImageSequence.py -> build/lib.macosx-10.15-x86_64-3.8/PIL
    copying src/PIL/PyAccess.py -> build/lib.macosx-10.15-x86_64-3.8/PIL
    copying src/PIL/_binary.py -> build/lib.macosx-10.15-x86_64-3.8/PIL
    copying src/PIL/Image.py -> build/lib.macosx-10.15-x86_64-3.8/PIL
    copying src/PIL/__main__.py -> build/lib.macosx-10.15-x86_64-3.8/PIL
    copying src/PIL/XVThumbImagePlugin.py -> build/lib.macosx-10.15-x86_64-3.8/PIL
    copying src/PIL/SgiImagePlugin.py -> build/lib.macosx-10.15-x86_64-3.8/PIL
    copying src/PIL/ImImagePlugin.py -> build/lib.macosx-10.15-x86_64-3.8/PIL
    copying src/PIL/PsdImagePlugin.py -> build/lib.macosx-10.15-x86_64-3.8/PIL
    copying src/PIL/JpegImagePlugin.py -> build/lib.macosx-10.15-x86_64-3.8/PIL
    copying src/PIL/ImageFont.py -> build/lib.macosx-10.15-x86_64-3.8/PIL
    copying src/PIL/PpmImagePlugin.py -> build/lib.macosx-10.15-x86_64-3.8/PIL
    copying src/PIL/FtexImagePlugin.py -> build/lib.macosx-10.15-x86_64-3.8/PIL
    running egg_info
    writing src/Pillow.egg-info/PKG-INFO
    writing dependency_links to src/Pillow.egg-info/dependency_links.txt
    writing top-level names to src/Pillow.egg-info/top_level.txt
    reading manifest file 'src/Pillow.egg-info/SOURCES.txt'
    reading manifest template 'MANIFEST.in'
    warning: no files found matching '*.c'
    warning: no files found matching '*.h'
    warning: no files found matching '*.sh'
    warning: no previously-included files found matching '.appveyor.yml'
    warning: no previously-included files found matching '.coveragerc'
    warning: no previously-included files found matching '.codecov.yml'
    warning: no previously-included files found matching '.editorconfig'
    warning: no previously-included files found matching '.readthedocs.yml'
    warning: no previously-included files found matching 'azure-pipelines.yml'
    warning: no previously-included files matching '.git*' found anywhere in distribution
    warning: no previously-included files matching '*.pyc' found anywhere in distribution
    warning: no previously-included files matching '*.so' found anywhere in distribution
    no previously-included directories found matching '.azure-pipelines'
    no previously-included directories found matching '.travis'
    writing manifest file 'src/Pillow.egg-info/SOURCES.txt'
    running build_ext
    
    
    The headers or library files could not be found for zlib,
    a required dependency when compiling Pillow from source.
    
    Please see the install instructions at:
       https://pillow.readthedocs.io/en/latest/installation.html
    
    Traceback (most recent call last):
      File "/private/var/folders/sy/tzj820zd5vb4nv6wfgxcl2rr0000gn/T/pip-install-yasp_tsp/pillow/setup.py", line 852, in <module>
        setup(
      File "/Users/agibson/Documents/GitHub/bedrock/venv/lib/python3.8/site-packages/setuptools/__init__.py", line 144, in setup
        return distutils.core.setup(**attrs)
      File "/usr/local/Cellar/python@3.8/3.8.5/Frameworks/Python.framework/Versions/3.8/lib/python3.8/distutils/core.py", line 148, in setup
        dist.run_commands()
      File "/usr/local/Cellar/python@3.8/3.8.5/Frameworks/Python.framework/Versions/3.8/lib/python3.8/distutils/dist.py", line 966, in run_commands
        self.run_command(cmd)
      File "/usr/local/Cellar/python@3.8/3.8.5/Frameworks/Python.framework/Versions/3.8/lib/python3.8/distutils/dist.py", line 985, in run_command
        cmd_obj.run()
      File "/Users/agibson/Documents/GitHub/bedrock/venv/lib/python3.8/site-packages/setuptools/command/install.py", line 61, in run
        return orig.install.run(self)
      File "/usr/local/Cellar/python@3.8/3.8.5/Frameworks/Python.framework/Versions/3.8/lib/python3.8/distutils/command/install.py", line 545, in run
        self.run_command('build')
      File "/usr/local/Cellar/python@3.8/3.8.5/Frameworks/Python.framework/Versions/3.8/lib/python3.8/distutils/cmd.py", line 313, in run_command
        self.distribution.run_command(command)
      File "/usr/local/Cellar/python@3.8/3.8.5/Frameworks/Python.framework/Versions/3.8/lib/python3.8/distutils/dist.py", line 985, in run_command
        cmd_obj.run()
      File "/usr/local/Cellar/python@3.8/3.8.5/Frameworks/Python.framework/Versions/3.8/lib/python3.8/distutils/command/build.py", line 135, in run
        self.run_command(cmd_name)
      File "/usr/local/Cellar/python@3.8/3.8.5/Frameworks/Python.framework/Versions/3.8/lib/python3.8/distutils/cmd.py", line 313, in run_command
        self.distribution.run_command(command)
      File "/usr/local/Cellar/python@3.8/3.8.5/Frameworks/Python.framework/Versions/3.8/lib/python3.8/distutils/dist.py", line 985, in run_command
        cmd_obj.run()
      File "/usr/local/Cellar/python@3.8/3.8.5/Frameworks/Python.framework/Versions/3.8/lib/python3.8/distutils/command/build_ext.py", line 340, in run
        self.build_extensions()
      File "/private/var/folders/sy/tzj820zd5vb4nv6wfgxcl2rr0000gn/T/pip-install-yasp_tsp/pillow/setup.py", line 687, in build_extensions
        raise RequiredDependencyException(f)
    __main__.RequiredDependencyException: zlib
    
    During handling of the above exception, another exception occurred:
    
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/private/var/folders/sy/tzj820zd5vb4nv6wfgxcl2rr0000gn/T/pip-install-yasp_tsp/pillow/setup.py", line 902, in <module>
        raise RequiredDependencyException(msg)
    __main__.RequiredDependencyException:
    
    The headers or library files could not be found for zlib,
    a required dependency when compiling Pillow from source.
    
    Please see the install instructions at:
       https://pillow.readthedocs.io/en/latest/installation.html
    
    
    ----------------------------------------
ERROR: Command errored out with exit status 1: /Users/agibson/Documents/GitHub/bedrock/venv/bin/python3 -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/private/var/folders/sy/tzj820zd5vb4nv6wfgxcl2rr0000gn/T/pip-install-yasp_tsp/pillow/setup.py'"'"'; __file__='"'"'/private/var/folders/sy/tzj820zd5vb4nv6wfgxcl2rr0000gn/T/pip-install-yasp_tsp/pillow/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' install --record /private/var/folders/sy/tzj820zd5vb4nv6wfgxcl2rr0000gn/T/pip-record-v18v5jll/install-record.txt --single-version-externally-managed --compile --install-headers /Users/agibson/Documents/GitHub/bedrock/venv/include/site/python3.8/Pillow Check the logs for full command output.
```

### Environment

macOS 10.15.5

**Comment by alexgibson** [comment]
@pmac any idea as to how I can fix this? I can run the docker setup for most things, but for running tests locally the full install is still needed.

**Comment by pmac** [comment]
My guess is you upgraded to Python 3.8 and bedrock isn't ready for that. I recommend using PyEnv to manage Python versions.

**Comment by alexgibson** [comment]
I downgraded to Python 3.6.11 using the PyEnv library you suggested above and things are working again. Looks like both 3.7 and 3.8 still have issues.

I'll leave this issue open for reference should anyone else ahve trouble. Thanks again @pmac

**Comment by pmac** [comment]
Interesting. 3.7 should work. I use that locally and we use it in production. I'll do some testing.

**Comment by alexgibson** [comment]
I tried 3.7.8 and the install failed, at which point I went down to 3.6.11
