### ISSUE TITLE
Mozilla.UITour is undefined

### ISSUE THREAD

**Issue by alexgibson** [mozilla/bedrock#9690]
## Description

```
TypeError: Mozilla.UITour is undefined
  at ? (/media/js/BUNDLES/firefox_whatsnew_account.38c1dfc2dac0.js:1:47)
  at ? (/media/js/BUNDLES/firefox_whatsnew_account.38c1dfc2dac0.js:1:309)
```

Quite a frequent error on our /whatsnew pages: https://sentry.prod.mozaws.net/operations/bedrock-prod/issues/9874330/events/

This is likely caused by slow connectivity, but something we can likely fail more fracefully with.

**Comment by alexgibson** [comment]
Added a check for this in https://github.com/mozilla/bedrock/pull/9932
